import React from 'react';
import Head from 'next/head';
import { Col, Container, Row } from 'react-bootstrap';
import Test from 'components/atoms/Test';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container fluid>
        <Row>
          <Col>
            <p className="fs-1">Yay, its fluid!</p>
            <Test />
          </Col>
        </Row>
      </Container>
    </div>
  );
}
